"""first version

Revision ID: d1b9ab010313
Revises: 31f81d46afac
Create Date: 2025-03-14 16:01:52.081503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1b9ab010313'
down_revision: Union[str, None] = '31f81d46afac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation_details', sa.Column('reservation_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'reservation_details', 'reservations', ['reservation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservation_details', type_='foreignkey')
    op.drop_column('reservation_details', 'reservation_id')
    # ### end Alembic commands ###
